[functions.mp-create-preference]
verify_jwt = false

[functions.mp-confirm-return]
verify_jwt = false

[functions.mp-create-media-unlock]
verify_jwt = false

[functions.mp-confirm-media-return]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.share-profile]
verify_jwt = false

[functions.share-profile-v2]
verify_jwt = false
